#!/bin/sh
PLANTUML_VER="1.2022.6"
[ -f "/tmp/plantuml.${PLANTUML_VER}.jar" ] || wget -q "http://sourceforge.net/projects/plantuml/files/plantuml.${PLANTUML_VER}.jar/download" -O /tmp/plantuml.${PLANTUML_VER}.jar
java -Djava.awt.headless=true -jar /tmp/plantuml.${PLANTUML_VER}.jar ${@}
