[project]
name = "plantuml-markdown"
version = "3.11.3"
description = "A PlantUML plugin for Markdown"
authors = [
    { name = "Michele Tessaro" }
]
readme = "README.md"
classifiers = [
    "Programming Language :: Python",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Text Processing :: Filters",
    "Topic :: Text Processing :: Markup :: HTML"
]
keywords = ['Markdown', 'typesetting', 'include', 'plugin', 'extension']
requires-python = ">=3.11"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[dependency-groups]
dev = [
    "commitizen>=3.0,<4.0",
    "pre-commit>=3.0,<4.0",
    "setuptools>=44.1.1",
    "twine>=1.15.0",
]

[tool.commitizen]
version_provider = "pep621"
tag_format = "$version"
